spring:
  application:
    name: mortgate-service
  datasource:
    url: jdbc:mysql://localhost:3306/mort_home_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root123!
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


app:
  service:
    account-service: http://localhost:8081/accounts
