spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:6033/mort_account_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root123!
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
